package com.clinicwave.clinicwaveusermanagementservice.enums;

/**
 * This enum represents the different types of verification codes that can be generated by the system.
 * It includes values for email verification, phone verification, and password reset.
 *
 * @author aamir on 7/7/24
 */
public enum VerificationCodeTypeEnum {
  EMAIL_VERIFICATION,
  PHONE_VERIFICATION,
  PASSWORD_RESET,
  TWO_FACTOR_AUTHENTICATION,
  ACCOUNT_DELETION,
  EMAIL_CHANGE,
  PHONE_NUMBER_CHANGE
}
